### ISSUE TITLE
Hardcoded conversion webhook namespace in primary Karpenter helm chart incompatible with running in different namespaces

### ISSUE THREAD

**Issue by dschaaff** [kubernetes-sigs/karpenter#1597]
### Description

We run Karpenter in the `karpenter` namespace and not `kube-system`. This is primarily for historical reasons. We were early adopters of Karpenter and it is risky and not worthwhile to move the install over the kube-system namespace. We also do not use the karpenter-crd chart. Flux manages the helm install and has a feature to ensure CRDs are upgraded when the helm chart updates. See https://fluxcd.io/flux/components/helm/helmreleases/#controlling-the-lifecycle-of-custom-resource-definitions

The `Karpenter` chart installs CRDs with conversion webhooks client config [hardcoded to the kube-system namespace](https://github.com/aws/karpenter-provider-aws/blob/v0.37.1/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml#L1343). Unfortunately this now blocks us from updating to v1 without also migrating to the karpenter-crd chart. 

**Reproduction Steps**
Manage karpenter using flux with `crds: CreateReplace` set on the install and upgrade specs of the flux helmrelease manifest

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: karpenter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: karpenter
      version: 0.37.1
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
  interval: 10m0s
  releaseName: karpenter
  targetNamespace: karpenter
  storageNamespace: karpenter
```
- update to 0.37.1

The controller logs an error 

```
{"level":"INFO","time":"2024-08-23T15:23:56.820Z","logger":"controller","message":"k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.NodePool: conversion webhook for karpenter.sh/v1beta1, Kind=NodePool failed: Post \"https://karpenter.kube-system.svc:8443/conversion/karpenter.sh?timeout=30s\": service \"karpenter\" not found","commit":"5bdf9c3"}
karpenter-5657b5578c-w6wqj controller 
```

- upgrade controller to 1.0.0
- update nodepool and ec2nodeclass manifests to v1 apis

Flux returns a reconciliation error 

```
NodePool/default dry-run failed: failed to prune fields: failed add back owned items: failed to convert pruned object at version karpenter.sh/v1: conversion webhook for karpenter.sh/v1beta1, Kind=NodePool failed: Post "https://karpenter.karpenter.svc:8443/conversion/karpenter.sh?timeout=30s": EOF```
```

The controller logs this error at the same time 

```
{"level":"ERROR","time":"2024-08-22T19:17:35.731Z","logger":"webhook","message":"http: panic serving 10.13.219.69:48234: runtime error: invalid memory address or nil pointer dereference\ngoroutine 341367 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1903 +0xb0\npanic({0x2225100?, 0x4734a10?})\n\truntime/panic.go:770 +0x124\nsigs.k8s.io/karpenter/pkg/apis/v1.(*NodeClaimTemplate).convertFrom(0x4011dfb310, {0x2f1bb28, 0x401546b140}, 0x4001594708)\n\tsigs.k8s.io/karpenter@v1.0.0/pkg/apis/v1/nodepool_conversion.go:181 +0x188\nsigs.k8s.io/karpenter/pkg/apis/v1.(*NodePoolSpec).convertFrom(0x4011dfb310, {0x2f1bb28, 0x401546b140}, 0x4001594708)\n\tsigs.k8s.io/karpenter@v1.0.0/pkg/apis/v1/nodepool_conversion.go:145 +0xe8\nsigs.k8s.io/karpenter/pkg/apis/v1.(*NodePool).ConvertFrom(0x4011dfb208, {0x2f1bb28?, 0x401546b140?}, {0x2efd390?, 0x4001594600})\n\tsigs.k8s.io/karpenter@v1.0.0/pkg/apis/v1/nodepool_conversion.go:121 +0x124\nknative.dev/pkg/webhook/resourcesemantics/conversion.(*reconciler).convert(0x40008a4480, {0x2f1bb28, 0x401546aff0}, {{0x4011ddb600, 0x29f, 0x2c0}, {0x0, 0x0}}, {0x400bbc3fd0, 0xf})\n\tknative.dev/pkg@v0.0.0-20231010144348-ca8c009405dd/webhook/resourcesemantics/conversion/conversion.go:137 +0x119c\nknative.dev/pkg/webhook/resourcesemantics/conversion.(*reconciler).Convert(0x40008a4480, {0x2f1bb28?, 0x401546af90?}, 0x4011020f00)\n\tknative.dev/pkg@v0.0.0-20231010144348-ca8c009405dd/webhook/resourcesemantics/conversion/conversion.go:57 +0x174\nknative.dev/pkg/webhook.New.conversionHandler.func5({0x2f0c658, 0x4011b18540}, 0x4011dede60)\n\tknative.dev/pkg@v0.0.0-20231010144348-ca8c009405dd/webhook/conversion.go:66 +0x24c\nnet/http.HandlerFunc.ServeHTTP(0x4000be5400?, {0x2f0c658?, 0x4011b18540?}, 0x1d01d10?)\n\tnet/http/server.go:2171 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x401546ae40?, {0x2f0c658, 0x4011b18540}, 0x4011dede60)\n\tnet/http/server.go:2688 +0x1a4\nknative.dev/pkg/webhook.(*Webhook).ServeHTTP(0x4000be5380, {0x2f0c658, 0x4011b18540}, 0x4011dede60)\n\tknative.dev/pkg@v0.0.0-20231010144348-ca8c009405dd/webhook/webhook.go:310 +0xc4\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP(0x4000450150, {0x2f0c658, 0x4011b18540}, 0x4011dede60)\n\tknative.dev/pkg@v0.0.0-20231010144348-ca8c009405dd/network/handlers/drain.go:113 +0x158\nnet/http.serverHandler.ServeHTTP({0x2ef71d0?}, {0x2f0c658?, 0x4011b18540?}, 0x6?)\n\tnet/http/server.go:3142 +0xbc\nnet/http.(*conn).serve(0x40101fb680, {0x2f1bb28, 0x400097e1e0})\n\tnet/http/server.go:2044 +0x508\ncreated by net/http.(*Server).Serve in goroutine 294\n\tnet/http/server.go:3290 +0x3f0\n","commit":"5bdf9c3"}
```

This blocks the v1 upgrade for user's relying on flux when running Karpenter in any namespace besides kube-system.

**Expected Behavior**:

The karpenter helm chart should support being installed in any namespace with full functionality.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dschaaff** [comment]
I think this may be more appropriate on the AWS repo https://github.com/aws/karpenter-provider-aws/issues/6864

Feel free to close this issue if that is the case.

**Comment by jmdeal** [comment]
Yeah, you're correct. Closing to track this in the provider repo.
/close
